# Generated by Django 5.1.5 on 2025-01-20 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0010_alter_author_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(),
        ),
    ]
