# Generated by Django 5.1.5 on 2025-01-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookreview', '0012_alter_author_birth_date_alter_book_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.DateField(),
        ),
    ]
